#JPA
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.hibernate.naming-strategy=org.hibernate.cfg.ImprovedNamingStrategy

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

#for mapping
spring.mvc.view.prefix:/WEB-INF/jsp/
spring.mvc.view.suffix:.jsp

#allowPublicKeyRetrieval=true&useSSL


server.port = 8089

#H2 via Environment Variables
spring.datasource.driver-class-name=${spring.datasource.driver-class-name:org.h2.Driver}
spring.datasource.url=${spring.datasource.url:jdbc:h2:mem:hoteldb;DB_CLOSE_DELAY=-1}
spring.datasource.username=${spring.datasource.username:sa}
spring.datasource.password=${spring.datasource.password:}
spring.h2.console.enabled=true
